### ISSUE TITLE
PC端乱码

### ISSUE THREAD

**Issue by comradexy** [WisteFinch/Helldivers2CallForStratagemsOnPhone#16]
![image](https://github.com/user-attachments/assets/c450e349-5ac4-4b2c-a8ec-78196a0768f5)

PC端打开后终端内显示乱码，请问如何解决？

**Comment by WisteFinch** [comment]
去微软商店里下载Windows Terminal替换掉原版CMD应用
![image](https://github.com/user-attachments/assets/0ae0dfae-5425-4dea-b4b4-120250e9dc3c)
